# Generated by Django 3.0.7 on 2020-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(blank=True, max_length=50, null=True)),
                ('l_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField()),
                ('member', models.BooleanField()),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
